

trigger:
- master

pool:

  vmImage: "vs2017-win2016"

steps:
- task: UiPathInstallPlatform-preview@2

- task: CmdLine@2
  inputs:
    script: 'dir' 
    
    

- task: UiPathPack@2
  inputs:
    versionType: AutoVersion # Options: AutoVersion, CurrentVersion, ManualVersion 
    version: '1.0.0' # Required when versionType == ManualVersion
    projectJsonPath: '$(Build.ArtifactStagingDirectory)\RPA Testing\project.json'
    outputType: 'Process'
    orchestratorConnection: 'Orchestrator'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'

