

trigger:
- master

pool:

  vmImage: "vs2017-win2016"

steps:
- task: UiPathInstallPlatform-preview@2

- task: UiPathAssets@2
  inputs:
    orchestratorConnection: 'Orchestrator'
    folderName: 'ThomasStocker_modern_folder'
    assetActionType: 'Deploy'
    csvFile: 'assets.csv'

- task: UiPathRunJob@2
  inputs:
    orchestratorConnection: 'Orchestrator'
    processName: 'RunJob'
    folderName: 'ThomasStocker_modern_folder'
    user: 'laptop-2flmrhn0\thomas stocker'