

trigger:
- master

pool:

  vmImage: "vs2017-win2016"

steps:
- task: UiPathInstallPlatform-preview@2

- task: CmdLine@2
  inputs:
    script: 'dir' 
    
    

- task: UiPathPack@2
  inputs:
    versionType: AutoVersion # Options: AutoVersion, CurrentVersion, ManualVersion 
    version: '1.0.0' # Required when versionType == ManualVersion
    projectJsonPath: 'RPA Testing\project.json'
    outputType: 'Process'
    orchestratorConnection: 'Orchestrator'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'



- task: UiPathTest@2
  inputs:
    testTarget: 'TestProject'
    orchestratorConnection: 'Orchestrator'
    testProjectPath: 'RPA Testing\project.json'
    environment: 'ThomasStockerEnvironment'
    folderName: 'ThomasStocker'
    testReportDestination: 'result.xml'