# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'



- task: UiPathPack@2
    inputs:
    versionType: 'AutoVersion'
      projectJsonPath: '$(Build.ArtifactStagingDirectory)\PAC_RPA-Testing\RPA Testing'
      outputType: 'Process'
      orchestratorConnection: 'Orchestrator'
      outputPath: '$(Build.ArtifactStagingDirectory)\Output'


